Feature/cmake lists env var for lib paths
crose72/OperationSquirrel pull request #28
Opened 2024-11-18 02:27 UTC by sbow

[Standardize platform options and update build configs](https://github.com/crose72/OperationSquirrel/commit/4542732fcbf78e95ca09917fe32b347825f05e7a) 

Updated .gitignore to include new paths for env_config.json, data, and build directories.

Updated Building-SquirrelDefender.md to reflect the new CMake version (3.28) and changed platform option names from JETSON_B01 to BLD_JETSON_B01.

Updated CMakeLists.txt:
- Changed the minimum required CMake version from 2.8 to 3.10.
- Added detailed comments and environment variable options for both Windows and Jetson builds.
- Renamed platform options from JETSON_B01, WSL, and WIN32 to BLD_JETSON_B01, BLD_WSL, and BLD_WIN.
- Added validation and inclusion of environment variables for library paths.
- Updated platform-specific configurations and library linking.

Added CMakeSettings.json to define build configurations for x64-Debug and x64-Release using the Ninja generator.

Updated various header files to replace JETSON_B01 and _WIN32 with BLD_JETSON_B01 and BLD_WIN respectively.

Updated source files to use the new platform definitions for initialization, looping, and shutdown functions.

Added new environment configuration files (env_config.json, set_jetson_env_config.sh, set_win_env_config.ps1) to manage environment variables for different platforms.

Created set_wsl_env_config.sh script to read a JSON configuration file and set environment variables for WSL.

2024-11-22 05:21 UTC, sbow commented
[Working - follows on BLD_WIN.](https://github.com/crose72/OperationSquirrel/pull/28/commits/c9abfce4762d3c4d445bea9ea98e615707de31ca) 
[c9abfce](https://github.com/crose72/OperationSquirrel/pull/28/commits/c9abfce4762d3c4d445bea9ea98e615707de31ca)
-- also, got Debug target working in Visual Studio

Enhance build config and improve initialization

Updated .gitignore to include additional directories and files.
Modified CMakeLists.txt to:
  - Add platform-specific compiler flags for MSVC and GCC/Clang.
  - Introduce set_target_debug_flags function for specific targets.
  - Include environment variable-based paths for OpenCV when USE_ENV_VAR is defined.
  - Adjust build process for Jetson, WSL, and Windows platforms.
  - Update linking process for Windows to include OpenCV and other libraries.
  - Update linked libraries list for Windows, particularly for cuDNN.
Removed CMakeSettings.json configurations for x64-Debug and x64-Release.
Added initialization of yolo_detections vector in YOLO::init method.
Included <chrono> and <thread> headers in main.cpp.
Added a sleep delay in the main function after the first loop iteration.
Added a commented-out call to test_flight in VehicleController::loop method.

These changes enhance the build configuration for different platforms, improve the initialization of the YOLO detection vector, and introduce a delay in the main loop to ensure proper startup timing. Additionally, the .gitignore updates help manage the project's file structure more effectively.

2024-11-24 22:46 UTC, crose72 requested changes
I've requested a few changes to the code and cmake file.  One final change is for all changes to the folder inside of `SquirrelDefender\inc` to be unstaged and uncommited.

2024-11-24 22:46 UTC, crose72 commented on SquirrelDefender/CMakeLists.txt
> +    if(BLD_WIN)
I would rewrite 238-249 to something like the following.  This is for the option without using environment variables.  OpenCV directory is already being looked for so we can remove that.  And CUDA should be able to remain the same.  For TensorRT we don't want someone to manually change the cmake file so we can manually add the path when using the cmake gui in windows.

 ```
   if(BLD_WIN)
		set(TENSORRT_INCLUDE_DIR "C:/TensorRT/TensorRT-10.4.0.26/include" CACHE PATH "Path to TensorRT include directory")
        
		include_directories(
			${TENSORRT_INCLUDE_DIR}
            "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.6/include"
        )
		
		set(TENSORRT_LIB_DIR "C:/TensorRT/TensorRT-10.4.0.26/lib" CACHE PATH "Path to TensorRT library directory")
		
        link_directories(
			${TENSORRT_LIB_DIR}
            "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.6/lib/x64"
        )
```

2025-01-05 05:38 UTC, crose72 approved these changes
Updated the commit with the requested changes.  Ready to merge.

2025-01-05 05:39 UTC, merged